### ISSUE TITLE
Uncaught exceptions

### ISSUE THREAD

**Issue by grynn-in** [libracore/erpnextswiss#59] opened 2019-02-26 20:06 UTC
### Expected behvauour
No Errors

### Actual behaviour
//////////////////////////////
Uncaught exceptions
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 61, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1026, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/notifications.py", line 284, in get_open_count
    filters=filters, limit=100, distinct=True, ignore_ifnull=True))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1281, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1254, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 93, in execute
    result = self.build_and_run()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/db_query.py", line 117, in build_and_run
    return frappe.db.sql(query, as_dict=not self.as_list, debug=self.debug, update=self.update)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/database.py", line 210, in sql
    self._cursor.execute(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 165, in execute
    result = self._query(query)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 860, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1061, in _read_query_result
    result.read()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1349, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 1018, in _read_packet
    packet.check_error()
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/connections.py", line 384, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (1054, u"Unknown column 'tabPayment Entry.customer' in 'where clause'")

/////////////////////////////////////////

### Observed in (version)
v11.1.11, erpnext
v11.1.11, frappe
v1.3.0, erpnext swiss

### Steps to reproduce
When you change/access Master such as customer  / supplier

**Comment by lasalesi** [comment] 2019-03-02 19:03
Hi @grynn-in,
thanks for reporting your issue. 'tabPayment Entry.customer' should be 'tabPayment Entry.group', however, I cannot reproduce the issue and the trace does not give a hint that this is caused by ERPNextSwiss. Are there any custom scripts in use?

Any more details to get this reproduced?

**Comment by grynn-in** [comment] 2019-03-03 07:56
Thanks for trying out out. 
It's an out of the box install. V11.

**Comment by lasalesi** [comment] 2019-03-07 13:02
Sorry, cannot reproduce the above error with
* installed a fresh production instance on a Debian server
* installed ERPNextSwiss
* created and navigated between customers

![grafik](https://user-images.githubusercontent.com/26505250/53958136-89303280-40e0-11e9-8b94-d1c7d913592b.png)

The payment entry table does not have (and does not need) a `customer` field:

	+-----------------------------+---------------+------+-----+----------+-------+
	| Field                       | Type          | Null | Key | Default  | Extra |
	+-----------------------------+---------------+------+-----+----------+-------+
	| name                        | varchar(140)  | NO   | PRI | NULL     |       |
	| creation                    | datetime(6)   | YES  |     | NULL     |       |
	| modified                    | datetime(6)   | YES  | MUL | NULL     |       |
	| modified_by                 | varchar(140)  | YES  |     | NULL     |       |
	| owner                       | varchar(140)  | YES  |     | NULL     |       |
	| docstatus                   | int(1)        | NO   |     | 0        |       |
	| parent                      | varchar(140)  | YES  | MUL | NULL     |       |
	| parentfield                 | varchar(140)  | YES  |     | NULL     |       |
	| parenttype                  | varchar(140)  | YES  |     | NULL     |       |
	| idx                         | int(8)        | NO   |     | 0        |       |
	| total_allocated_amount      | decimal(18,6) | NO   |     | 0.000000 |       |
	| contact_email               | varchar(140)  | YES  |     | NULL     |       |
	| naming_series               | varchar(140)  | YES  |     | NULL     |       |
	| payment_order               | varchar(140)  | YES  |     | NULL     |       |
	| reference_no                | varchar(140)  | YES  |     | NULL     |       |
	| paid_to                     | varchar(140)  | YES  |     | NULL     |       |
	| base_paid_amount            | decimal(18,6) | NO   |     | 0.000000 |       |
	| letter_head                 | varchar(140)  | YES  |     | NULL     |       |
	| _liked_by                   | text          | YES  |     | NULL     |       |
	| reference_date              | date          | YES  | MUL | NULL     |       |
	| cost_center                 | varchar(140)  | YES  |     | NULL     |       |
	| received_amount             | decimal(18,6) | NO   |     | 0.000000 |       |
	| unallocated_amount          | decimal(18,6) | NO   |     | 0.000000 |       |
	| allocate_payment_amount     | int(1)        | NO   |     | 1        |       |
	| target_exchange_rate        | decimal(18,6) | NO   |     | 0.000000 |       |
	| title                       | varchar(140)  | YES  |     | NULL     |       |
	| party_type                  | varchar(140)  | YES  | MUL | NULL     |       |
	| base_total_allocated_amount | decimal(18,6) | NO   |     | 0.000000 |       |
	| bank_account                | varchar(140)  | YES  |     | NULL     |       |
	| party                       | varchar(140)  | YES  |     | NULL     |       |
	| base_received_amount        | decimal(18,6) | NO   |     | 0.000000 |       |
	| _comments                   | text          | YES  |     | NULL     |       |
	| payment_type                | varchar(140)  | YES  |     | NULL     |       |
	| source_exchange_rate        | decimal(18,6) | NO   |     | 0.000000 |       |
	| clearance_date              | date          | YES  |     | NULL     |       |
	| paid_from_account_balance   | decimal(18,6) | NO   |     | 0.000000 |       |
	| company                     | varchar(140)  | YES  |     | NULL     |       |
	| _assign                     | text          | YES  |     | NULL     |       |
	| paid_from                   | varchar(140)  | YES  |     | NULL     |       |
	| party_balance               | decimal(18,6) | NO   |     | 0.000000 |       |
	| party_name                  | varchar(140)  | YES  |     | NULL     |       |
	| mode_of_payment             | varchar(140)  | YES  |     | NULL     |       |
	| remarks                     | text          | YES  |     | NULL     |       |
	| _user_tags                  | text          | YES  |     | NULL     |       |
	| bank                        | varchar(140)  | YES  |     | NULL     |       |
	| bank_account_no             | varchar(140)  | YES  |     | NULL     |       |
	| paid_to_account_currency    | varchar(140)  | YES  |     | NULL     |       |
	| paid_from_account_currency  | varchar(140)  | YES  |     | NULL     |       |
	| paid_to_account_balance     | decimal(18,6) | NO   |     | 0.000000 |       |
	| paid_amount                 | decimal(18,6) | NO   |     | 0.000000 |       |
	| amended_from                | varchar(140)  | YES  |     | NULL     |       |
	| project                     | varchar(140)  | YES  |     | NULL     |       |
	| auto_repeat                 | varchar(140)  | YES  |     | NULL     |       |
	| difference_amount           | decimal(18,6) | NO   |     | 0.000000 |       |
	| posting_date                | date          | YES  |     | NULL     |       |
	| contact_person              | varchar(140)  | YES  |     | NULL     |       |
	| print_heading               | varchar(140)  | YES  |     | NULL     |       |
	| transaction_type            | varchar(140)  | YES  |     | NULL     |       |
	| iban                        | varchar(140)  | YES  |     | NULL     |       |
	| bic                         | varchar(140)  | YES  |     | NULL     |       |
	| esr_participant_number      | varchar(140)  | YES  |     | NULL     |       |
	| esr_reference               | varchar(140)  | YES  |     | NULL     |       |
	| camt_amount                 | decimal(18,6) | NO   |     | 0.000000 |       |
	| exported_to_abacus          | int(1)        | NO   |     | 0        |       |
	+-----------------------------+---------------+------+-----+----------+-------+

**Comment by lasalesi** [comment] 2019-03-28 09:59
This issue will be closed as not reproducible in 3 days...

**Closed** 2019-04-01 06:46 UTC
